language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

branches:
  except:
    - /^release-.*$/

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
    - php: 5.6
      env:
        - DEPS=latest
        - CHECK_CS=true
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
    - php: 7
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest

before_install:
  - travis_retry composer self-update
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

script:
  ## PHP_CodeSniffer
#  - php vendor/bin/phpcs --report=emacs --standard=PSR1 src
#  - php vendor/bin/phpcs --report=emacs --standard=PSR2 src
  ## PHP Copy/Paste Detector
#  - php vendor/bin/phpcpd --verbose src
  ## PHP Mess Detector
#  - php vendor/bin/phpmd src text cleancode
#  - php vendor/bin/phpmd src text codesize
#  - php vendor/bin/phpmd src text controversial
#  - php vendor/bin/phpmd src text design
#  - php vendor/bin/phpmd src text naming
#  - php vendor/bin/phpmd src text unusedcode
  ## PHPLOC
#  - php vendor/bin/phploc src
  ## PHPUNIT
#  - php vendor/bin/phpunit test
  - composer unittest
  - if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi

notifications:
  email: true
