<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MBtec\Email\Module'                       => __DIR__ . '/Module.php',
  'MBtec\Email\Service\Transport'            => __DIR__ . '/src/Email/Service/Transport.php',
  'MBtec\Email\Service\HtmlConverter'        => __DIR__ . '/src/Email/Service/HtmlConverter.php',
  'MBtec\Email\Service\Renderer'             => __DIR__ . '/src/Email/Service/Renderer.php',
  'MBtec\Email\Service\Email'                => __DIR__ . '/src/Email/Service/Email.php',
  'MBtec\Email\Exception\ExceptionInterface' => __DIR__ . '/src/Email/Exception/ExceptionInterface.php',
  'MBtec\Email\Exception\RuntimeException'   => __DIR__ . '/src/Email/Exception/RuntimeException.php',
);
